---
- name: Disable IPv6 via sysctl
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: '1'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/99-disable-ipv6.conf
  loop:
    - { name: 'net.ipv6.conf.all.disable_ipv6' }
    - { name: 'net.ipv6.conf.default.disable_ipv6' }
    - { name: 'net.ipv6.conf.lo.disable_ipv6' }

- name: Add kernel parameter to GRUB to disable IPv6
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="ipv6.disable=1"'
    backrefs: yes
  notify: Update GRUB