---
- name: Ensure the package list is updated
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache valid for 1 hour to avoid unnecessary updates

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes  # Use apt-get instead of aptitude

# Update the apt cache
- name: Install common set of apts
  import_tasks: common_pkgs.yaml
  tags: 
    - setup

- name: Remove unnecessary packages and dependencies
  ansible.builtin.apt:
    autoremove: yes
    purge: yes

- name: Clean up the local repository of retrieved package files
  ansible.builtin.apt:
    autoclean: yes

# Setup zsh for users
- name: Setup zsh common
  import_tasks: setup_zsh_common.yaml
  tags: 
    - setup

# Include tasks from an external file
- name: Check if ssh key exit and create if not
  import_tasks: create_key.yaml
  tags: 
    - setup

# Include tasks from an external file
- name: Disable IPv6
  import_tasks: disable_ipv6.yaml
  tags: 
    - setup    