## Proxmox Hypervisor Clusters
---
k8s: #coma
  hosts:
    k8s-node-1:
      ansible_host: 10.0.0.192
    #k8s-node-2:
    #  ansible_host: 10.0.0.129
    #k8s-node-3:
    #  ansible_host: 10.0.0.153      

pve_cluster: #universe
  hosts:
    alone:
      ansible_host: 10.0.0.135
    storage:
      ansible_host: 10.0.0.17
    higgs:
      ansible_host: 10.0.0.100
    beast:
      ansible_host: 10.0.0.44
    rog17:
      ansible_host: 10.0.0.77  

# Group containing all Debian hosts using children
debian_hosts:
  children:
    #pve_cluster:
    k8s:    