## Proxmox Hypervisor Clusters
hypervisors:
   hosts:
    storage:
      ansible_host: 10.0.0.17
    beast:
      ansible_host: 10.0.0.44
    rog17:
      ansible_host: 10.0.0.77
    higgs:
      ansible_host: 10.0.0.100
    alone:
      ansible_host: 10.0.0.135
    pve1:
      ansible_host: 10.0.0.192

probe:
  hosts:
    probe_ants:
      ansible_host: 10.0.33.199
    probe_dmz:
      ansible_host: 10.0.80.199
    probe_internet:
      ansible_host: 10.0.99.199
    probe_vm:
      ansible_host: 10.10.10.199
    probe_cam:
      ansible_host: 192.168.5.199

portainer:
  hosts:
    portainer:
      ansible_host: 10.10.10.9